import type { CommunityIconKey } from '@app/shared';
import {
  AppWindow,
  BookOpen,
  Calendar,
  Camera,
  Cloud,
  CreditCard,
  Database,
  Globe,
  HelpCircle,
  KeyRound,
  Laptop,
  Mail,
  Phone,
  Printer,
  ShieldCheck,
  Users,
  Wifi,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

/** Значки сообществ — готовый набор; цвет всегда из токенов темы. */
export const COMMUNITY_ICON_MAP: Record<CommunityIconKey, { icon: LucideIcon; label: string }> = {
  mail: { icon: Mail, label: 'Почта' },
  key: { icon: KeyRound, label: 'Ключ' },
  wifi: { icon: Wifi, label: 'Сеть' },
  laptop: { icon: Laptop, label: 'Ноутбук' },
  app: { icon: AppWindow, label: 'Программа' },
  help: { icon: HelpCircle, label: 'Вопрос' },
  printer: { icon: Printer, label: 'Принтер' },
  phone: { icon: Phone, label: 'Телефон' },
  shield: { icon: ShieldCheck, label: 'Безопасность' },
  users: { icon: Users, label: 'Люди' },
  database: { icon: Database, label: 'Данные' },
  cloud: { icon: Cloud, label: 'Облако' },
  book: { icon: BookOpen, label: 'Инструкции' },
  wrench: { icon: Wrench, label: 'Ремонт' },
  calendar: { icon: Calendar, label: 'Календарь' },
  globe: { icon: Globe, label: 'Сайты' },
  camera: { icon: Camera, label: 'Камера' },
  card: { icon: CreditCard, label: 'Карты и оплата' },
};
